---
title: Lib Dem Leadership Education Report
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Lib Dem Leadership Education Report
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
